version: '3.8'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: '1'

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
